fix(frontend/types): Add 'id' attribute to ChatMessageData
Solving previous build error:
- src/views/ChatView.vue(46,64): error TS2339: Property 'id' does not exist on type '{ nickname: string; content: string; timestamp: string; }'.