fix(frontend/types): Accept null error messages at FormInput
Previously causing errors:

- src/views/SignupView.vue(183,12): error TS2322: Type 'string | null' is not assignable to type 'string | undefined'.
      Type 'null' is not assignable to type 'string | undefined'.

- src/views/SignupView.vue(192,12): error TS2322: Type 'string | null' is not assignable to type 'string | undefined'.
      Type 'null' is not assignable to type 'string | undefined'.

- src/views/SignupView.vue(218,12): error TS2322: Type 'string | null' is not assignable to type 'string | undefined'.
      Type 'null' is not assignable to type 'string | undefined'.